# Generated by Django 5.1.7 on 2025-04-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="financial_info_completed",
            field=models.BooleanField(default=False),
        ),
    ]
